-- Schema for the marimo + Aiven PostgreSQL persistence demo.
-- api.py creates these tables itself on startup (CREATE TABLE IF NOT
-- EXISTS), so running this file by hand is optional -- it's kept here so
-- the schema is easy to read/reproduce against any PostgreSQL instance
-- (Aiven or otherwise) without spinning up the API first.
--
-- "key" is an anonymous per-browser session id generated by notebook.py
-- (see api.py) -- every visitor gets their own row, not a single shared one.

-- Key/value store holding the *current* value of every visitor's widgets.
CREATE TABLE IF NOT EXISTS app_state (
    key         TEXT PRIMARY KEY,
    value       JSONB NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Append-only audit log of every change, proving state really survives
-- notebook restarts and comes from Postgres rather than memory.
CREATE TABLE IF NOT EXISTS state_history (
    id          BIGSERIAL PRIMARY KEY,
    key         TEXT NOT NULL,
    value       JSONB NOT NULL,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS state_history_key_changed_at_idx
    ON state_history (key, changed_at DESC);
